-- Generated from the user's Guns of Marz 42.16 source scripts.
local data = {}

data.magazines = {
    ["MarzGuns.12GMagazine20_AA12"] = { "MarzGuns.AA12" },
    ["MarzGuns.12GMagazine8_AA12"] = { "MarzGuns.AA12" },
    ["MarzGuns.3006Clip8"] = { "MarzGuns.M1_GARAND" },
    ["MarzGuns.3006Magazine20_BAR"] = { "MarzGuns.BAR" },
    ["MarzGuns.357SpeedLoader6_PYTHON"] = { "MarzGuns.PYTHON" },
    ["MarzGuns.45Magazine100_THOMPSON"] = { "MarzGuns.THOMPSON" },
    ["MarzGuns.45Magazine12_USP"] = { "MarzGuns.USP" },
    ["MarzGuns.45Magazine20_THOMPSON"] = { "MarzGuns.THOMPSON" },
    ["MarzGuns.45Magazine20_USP"] = { "MarzGuns.USP" },
    ["MarzGuns.45Magazine30_MAC10"] = { "MarzGuns.MAC10" },
    ["MarzGuns.45Magazine30_THOMPSON"] = { "MarzGuns.THOMPSON" },
    ["MarzGuns.45Magazine40_MAC10"] = { "MarzGuns.MAC10" },
    ["MarzGuns.45Magazine7_M1911"] = { "MarzGuns.M1911" },
    ["MarzGuns.50Magazine12_DEAGLE"] = { "MarzGuns.DEAGLE" },
    ["MarzGuns.50Magazine8_DEAGLE"] = { "MarzGuns.DEAGLE" },
    ["MarzGuns.545x39Magazine30_Bakelite"] = { "MarzGuns.AK74", "MarzGuns.AKS74U" },
    ["MarzGuns.545x39Magazine45_Bakelite"] = { "MarzGuns.AK74", "MarzGuns.AKS74U" },
    ["MarzGuns.556x45Magazine100_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine150_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine20_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine25_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine30_G36"] = { "MarzGuns.G36", "MarzGuns.G36C" },
    ["MarzGuns.556x45Magazine30_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine50_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine60_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.556x45Magazine75_STANAG"] = { "MarzGuns.AR15", "MarzGuns.CAR15", "MarzGuns.FAMAS", "MarzGuns.FNC", "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.M4", "MarzGuns.M4A1", "MarzGuns.XM177" },
    ["MarzGuns.762x39Magazine30"] = { "MarzGuns.AK47" },
    ["MarzGuns.762x39Magazine75"] = { "MarzGuns.AK47" },
    ["MarzGuns.762x51Box100_M60"] = { "MarzGuns.M60" },
    ["MarzGuns.762x51Magazine20_FAL"] = { "MarzGuns.FAL" },
    ["MarzGuns.762x51Magazine20_G3"] = { "MarzGuns.G3" },
    ["MarzGuns.762x51Magazine20_M14"] = { "MarzGuns.M14" },
    ["MarzGuns.762x51Magazine5_M24"] = { "MarzGuns.M24" },
    ["MarzGuns.762x51Magazine5_PSG1"] = { "MarzGuns.PSG1" },
    ["MarzGuns.762x54Magazine10_SVD"] = { "MarzGuns.SVD" },
    ["MarzGuns.762x54StripperClip5_MOSIN"] = { "MarzGuns.MOSIN" },
    ["MarzGuns.9x19Magazine100_MP5"] = { "MarzGuns.MP5", "MarzGuns.MP5A2", "MarzGuns.MP5K", "MarzGuns.MP5SD" },
    ["MarzGuns.9x19Magazine10_P226"] = { "MarzGuns.P226" },
    ["MarzGuns.9x19Magazine13_HIPOWER"] = { "MarzGuns.HIPOWER" },
    ["MarzGuns.9x19Magazine15_M92FS"] = { "MarzGuns.M92FS" },
    ["MarzGuns.9x19Magazine18_M93R"] = { "MarzGuns.M93R" },
    ["MarzGuns.9x19Magazine18_VP70M"] = { "MarzGuns.VP70M" },
    ["MarzGuns.9x19Magazine20_MP5"] = { "MarzGuns.MP5", "MarzGuns.MP5A2", "MarzGuns.MP5K", "MarzGuns.MP5SD" },
    ["MarzGuns.9x19Magazine20_TEC9"] = { "MarzGuns.TEC9" },
    ["MarzGuns.9x19Magazine25_MP5"] = { "MarzGuns.MP5", "MarzGuns.MP5A2", "MarzGuns.MP5K", "MarzGuns.MP5SD" },
    ["MarzGuns.9x19Magazine30_M92FS"] = { "MarzGuns.M92FS" },
    ["MarzGuns.9x19Magazine30_MP5"] = { "MarzGuns.MP5", "MarzGuns.MP5A2", "MarzGuns.MP5K", "MarzGuns.MP5SD" },
    ["MarzGuns.9x19Magazine30_VP70M"] = { "MarzGuns.VP70M" },
    ["MarzGuns.9x19Magazine50_M92FS"] = { "MarzGuns.M92FS" },
    ["MarzGuns.9x19Magazine60_M93R"] = { "MarzGuns.M93R" },
    ["MarzGuns.9x19Magazine60_MP5"] = { "MarzGuns.MP5", "MarzGuns.MP5A2", "MarzGuns.MP5K", "MarzGuns.MP5SD" },
    ["MarzGuns.9x39Magazine30"] = { "MarzGuns.ASVAL" },
}

data.special = {
    ["MarzGuns.Picatinny_Rail"] = { "MarzGuns.M16A1", "MarzGuns.M16A2", "MarzGuns.M16A2_M203", "MarzGuns.M16A3", "MarzGuns.AR15", "MarzGuns.FNC", "MarzGuns.FAMAS", "MarzGuns.CAR15", "MarzGuns.XM177", "MarzGuns.M4A1", "MarzGuns.M14", "MarzGuns.FAL", "MarzGuns.G3", "MarzGuns.M24", "MarzGuns.MOSSBERG_590", "MarzGuns.BENELLI_M4", "MarzGuns.REMINGTON_870", "MarzGuns.PSG1", "MarzGuns.W1894", "MarzGuns.M1895", "MarzGuns.W1887", "MarzGuns.W1873", "MarzGuns.MP5", "MarzGuns.MP5A2", "MarzGuns.MP5SD", "MarzGuns.MP5K", "MarzGuns.AKS74U", "MarzGuns.ASVAL", "MarzGuns.G36", "MarzGuns.AA12", "MarzGuns.SVD", "MarzGuns.G36C" },
}

data.pretty = {
    ["MarzGuns.40mm_HE_Explosion"] = "40mm HE Explosion",
    ["MarzGuns.40mm_Incendiary_Explosion"] = "40mm Incendiary Explosion",
    ["MarzGuns.AA12"] = "AA-12",
    ["MarzGuns.AK47"] = "AK-47",
    ["MarzGuns.AK74"] = "AK-74",
    ["MarzGuns.AKS74U"] = "AKS-74U",
    ["MarzGuns.AR15"] = "AR-15",
    ["MarzGuns.ASVAL"] = "AS VAL",
    ["MarzGuns.Attack_Bayonet"] = "Attack Bayonet",
    ["MarzGuns.BAR"] = "Browning",
    ["MarzGuns.BENELLI_M4"] = "Benelli M4",
    ["MarzGuns.CAR15"] = "CAR-15",
    ["MarzGuns.COLT_SINGLE"] = "Colt Single Action",
    ["MarzGuns.DEAGLE"] = ".50 Desert Eagle",
    ["MarzGuns.DETECTIVE_38"] = "Detective .38",
    ["MarzGuns.DOUBLEBARREL"] = "Double Barrel",
    ["MarzGuns.Elvorenstein_Tacticool_Knife"] = "Elvorenstein Tacticool Knife",
    ["MarzGuns.FAL"] = "FN FAL",
    ["MarzGuns.FAMAS"] = "FAMAS",
    ["MarzGuns.FNC"] = "FN FNC",
    ["MarzGuns.G3"] = "G3",
    ["MarzGuns.G36"] = "G36",
    ["MarzGuns.G36C"] = "G36C",
    ["MarzGuns.HIPOWER"] = "Browning Hi-Power",
    ["MarzGuns.K98_BAYONET"] = "Karabiner 98k",
    ["MarzGuns.M14"] = "M14",
    ["MarzGuns.M14_Incendiary"] = "M14",
    ["MarzGuns.M16A1"] = "M16A1",
    ["MarzGuns.M16A2"] = "M16A2",
    ["MarzGuns.M16A2_M203"] = "M16A2 (M203)",
    ["MarzGuns.M16A3"] = "M16A3",
    ["MarzGuns.M18"] = "M18",
    ["MarzGuns.M1895"] = "Marlin 1895",
    ["MarzGuns.M1903"] = "M1903 Springfield",
    ["MarzGuns.M1911"] = "Colt M1911",
    ["MarzGuns.M1_GARAND"] = "M1 Garand",
    ["MarzGuns.M203_Weapon"] = "M203 Weapon",
    ["MarzGuns.M24"] = "M24",
    ["MarzGuns.M4"] = "M4",
    ["MarzGuns.M4A1"] = "M4A1",
    ["MarzGuns.M5_BAYONET"] = "M5",
    ["MarzGuns.M60"] = "M60",
    ["MarzGuns.M67"] = "M67",
    ["MarzGuns.M79"] = "M79",
    ["MarzGuns.M92FS"] = "Beretta M92FS",
    ["MarzGuns.M93R"] = "Beretta M93R",
    ["MarzGuns.M9_BAYONET"] = "M9",
    ["MarzGuns.MAC10"] = "Ingram MAC-10",
    ["MarzGuns.MASTERKEY"] = "Подствольный дробовик Masterkey",
    ["MarzGuns.MASTERKEY_Weapon"] = "Подствольный дробовик Masterkey",
    ["MarzGuns.MOSIN"] = "Mosin-Nagant",
    ["MarzGuns.MOSSBERG_590"] = "Mossberg 590",
    ["MarzGuns.MP412"] = "MP-412",
    ["MarzGuns.MP5"] = "MP5",
    ["MarzGuns.MP5A2"] = "MP5A2",
    ["MarzGuns.MP5K"] = "MP5K",
    ["MarzGuns.MP5SD"] = "MP5SD",
    ["MarzGuns.P226"] = "Sig Sauer P226",
    ["MarzGuns.PSG1"] = "PSG-1",
    ["MarzGuns.PYTHON"] = "Colt Python",
    ["MarzGuns.REMINGTON_870"] = "Remington 870",
    ["MarzGuns.RHINO"] = "Rhino",
    ["MarzGuns.SKS"] = "SKS",
    ["MarzGuns.SPAS12"] = "SPAS-12",
    ["MarzGuns.STEVENS_555"] = "Stevens 555",
    ["MarzGuns.SVD"] = "SVD",
    ["MarzGuns.SW629"] = "Smith & Wesson Model 629",
    ["MarzGuns.TEC9"] = "TEC-9",
    ["MarzGuns.THOMPSON"] = "Thompson",
    ["MarzGuns.TOZ34"] = "TOZ-34",
    ["MarzGuns.TRENCHGUN"] = "Trench",
    ["MarzGuns.USP"] = "Heckler & Koch USP",
    ["MarzGuns.VP70M"] = "Heckler & Koch VP70M",
    ["MarzGuns.W1873"] = "Winchester 1873",
    ["MarzGuns.W1873_CARBINE"] = "Winchester 1873",
    ["MarzGuns.W1887"] = "Winchester 1887",
    ["MarzGuns.W1894"] = "Winchester 1894",
    ["MarzGuns.XM177"] = "XM177",
}

data.params = {
    ["MarzGuns.12GMagazine20_AA12"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.12GMagazine8_AA12"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.12Gauge_Box_Buckshot"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox25;marzguns:ammobox" },
    ["MarzGuns.12Gauge_Box_Slug"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox25;marzguns:ammobox" },
    ["MarzGuns.12Gauge_Carton_Buckshot"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.12Gauge_Carton_Slug"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.12Gauge_Crate_Buckshot"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.12Gauge_Crate_Slug"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.12Gauge_Hull_Green"] = { tags = "hb:shotgunshell" },
    ["MarzGuns.12Gauge_Hull_Red"] = { tags = "hb:shotgunshell" },
    ["MarzGuns.12Gauge_Shell_Buckshot"] = { tags = "base:ammo;base:shotgunshell;marzguns:ammo25" },
    ["MarzGuns.12Gauge_Shell_Slug"] = { tags = "base:ammo;base:shotgunshell;marzguns:ammo25" },
    ["MarzGuns.223_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.223_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.223_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.223_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.223_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.22_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.3006Clip8"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.3006Magazine20_BAR"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.3006_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.3006_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.3006_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.3006_Casing"] = { tags = "hb:casing" },
    ["MarzGuns.3006_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.3030_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.3030_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.3030_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.3030_Casing"] = { tags = "hb:casing" },
    ["MarzGuns.3030_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.308_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.308_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.308_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.308_Casing"] = { tags = "hb:heavycasing" },
    ["MarzGuns.308_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.357SpeedLoader6_PYTHON"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.357_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.357_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.357_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.357_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.357_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.38_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.38_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.38_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.38_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.38_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.40mm_Box_Buckshot"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox10;marzguns:ammobox" },
    ["MarzGuns.40mm_Box_HE"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox10;marzguns:ammobox" },
    ["MarzGuns.40mm_Box_Incendiary"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox10;marzguns:ammobox" },
    ["MarzGuns.40mm_Casing"] = { tags = "hb:casing" },
    ["MarzGuns.40mm_Round_Buckshot"] = { tags = "base:ammo;marzguns:ammo10" },
    ["MarzGuns.40mm_Round_HE"] = { tags = "base:ammo;marzguns:ammo10" },
    ["MarzGuns.40mm_Round_Incendiary"] = { tags = "base:ammo;marzguns:ammo10" },
    ["MarzGuns.44_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.44_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.44_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.44_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.44_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.4570_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.4570_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.4570_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.4570_Casing"] = { tags = "hb:casing" },
    ["MarzGuns.4570_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.45Magazine100_THOMPSON"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.45Magazine12_USP"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.45Magazine20_THOMPSON"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.45Magazine20_USP"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.45Magazine30_MAC10"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.45Magazine30_THOMPSON"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.45Magazine40_MAC10"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.45Magazine7_M1911"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.45_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.45_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.45_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.45_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.45_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.45_Muzzle_Mount_Device"] = { mountOn = "MarzGuns.M1911;MarzGuns.USP;MarzGuns.MAC10" },
    ["MarzGuns.46x30_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.50Magazine12_DEAGLE"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.50Magazine8_DEAGLE"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.50_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.50_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.50_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.50_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.50_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.545x39Magazine100_Drum"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.545x39Magazine30_Bakelite"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.545x39Magazine45_Bakelite"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.545x39_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.545x39_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.545x39_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.545x39_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.545x39_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.556x45Magazine100_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine150_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine20_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine25_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine30_G36"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine30_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine50_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine60_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45Magazine75_STANAG"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.556x45_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.556x45_Box_ArmorPiercing"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.556x45_Box_HollowPoint"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.556x45_Box_Overpressured"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.556x45_Box_Subsonic"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.556x45_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.556x45_Bullet_ArmorPiercing"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.556x45_Bullet_HollowPoint"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.556x45_Bullet_Overpressured"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.556x45_Bullet_Subsonic"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.556x45_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.556x45_Carton_ArmorPiercing"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.556x45_Carton_HollowPoint"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.556x45_Carton_Overpressured"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.556x45_Carton_Subsonic"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.556x45_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.556x45_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.556x45_Crate_ArmorPiercing"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.556x45_Crate_HollowPoint"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.556x45_Crate_Overpressured"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.556x45_Crate_Subsonic"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.57x28_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.762x39Magazine30"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x39Magazine75"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x39_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.762x39_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.762x39_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.762x39_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.762x39_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.762x51Box100_M60"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x51Magazine20_FAL"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x51Magazine20_G3"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x51Magazine20_M14"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x51Magazine5_M24"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x51Magazine5_PSG1"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x51_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.762x51_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.762x51_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.762x51_Casing"] = { tags = "hb:casing" },
    ["MarzGuns.762x51_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.762x54Magazine10_SVD"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x54StripperClip5_MOSIN"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.762x54_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.762x54_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.762x54_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.762x54_Casing"] = { tags = "hb:heavycasing" },
    ["MarzGuns.762x54_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.792x57_Casing"] = { tags = "hb:casing" },
    ["MarzGuns.9x19Magazine100_MP5"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x19Magazine10_P226"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine13_HIPOWER"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine15_M92FS"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine18_M93R"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine18_VP70M"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine20_MP5"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x19Magazine20_TEC9"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x19Magazine25_MP5"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x19Magazine30_M92FS"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine30_MP5"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x19Magazine30_VP70M"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine50_M92FS"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine60_M93R"] = { mountOn = "MarzGuns.FakeItemPistols", tags = "base:hasmetal;base:pistolmagazine" },
    ["MarzGuns.9x19Magazine60_MP5"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x19_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox50;marzguns:ammobox" },
    ["MarzGuns.9x19_Bullet"] = { tags = "base:ammo;marzguns:ammo50" },
    ["MarzGuns.9x19_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.9x19_Casing"] = { tags = "hb:lightcasing" },
    ["MarzGuns.9x19_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.9x39Magazine30"] = { mountOn = "MarzGuns.FakeItemRifles", tags = "base:hasmetal;base:riflemagazine" },
    ["MarzGuns.9x39_Box"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:ammo;marzguns:ammobox20;marzguns:ammobox" },
    ["MarzGuns.9x39_Bullet"] = { tags = "base:ammo;marzguns:ammo20" },
    ["MarzGuns.9x39_Carton"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocarton" },
    ["MarzGuns.9x39_Casing"] = { tags = "hb:mediumcasing" },
    ["MarzGuns.9x39_Crate"] = { tags = "base:hasmetal;base:ignorezombiedensity;marzguns:ammocrate" },
    ["MarzGuns.AA12"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.AK47"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.AK74"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.AKS74U"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.AKS74U_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.AKS74U_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.AK_Mount"] = { mountOn = "MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47" },
    ["MarzGuns.AK_Muzzle_Mount_Device"] = { mountOn = "MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.AK47" },
    ["MarzGuns.AR15"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.AR_Muzzle_Mount_Device"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.M4;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.M4A1;MarzGuns.M16A2_M203" },
    ["MarzGuns.ASVAL"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.ASVAL_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.ASVAL_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.AimRight_Laser"] = { mountOn = "MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.ASVAL;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.M4" },
    ["MarzGuns.Aimpoint_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.Attack_Bayonet"] = { tags = "base:fishingspear;base:sharpenable;base:repairwithglue;base:repairwithtape;base:hasmetal" },
    ["MarzGuns.BAR"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.BAR_Integrated_Bipod_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.BAR_Integrated_Bipod_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.BENELLI_M4"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.Barrel_Close"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Barrel_Open"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Beretta_Mount"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226" },
    ["MarzGuns.Beretta_Stock_Deployed"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R" },
    ["MarzGuns.Beretta_Stock_Folded"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R" },
    ["MarzGuns.Bipod_Deployed"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.SVD;MarzGuns.PSG1;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.Bipod_Folded"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.SVD;MarzGuns.PSG1;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.Bolt_Fired"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bolt_Lock"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Booster_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.Booster_Scope_Off"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.BrightPoint-5_Light"] = { mountOn = "MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.ASVAL;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.M4", tags = "base:flashlight;base:usesbattery" },
    ["MarzGuns.Bullet_1"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_2"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_3"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_4"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_5"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_6"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_7"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_8"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Bullet_9"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.CAR15"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.CAR15_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.CAR15_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.COLT_SINGLE"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.Colt_Mount"] = { mountOn = "MarzGuns.M1911;MarzGuns.USP" },
    ["MarzGuns.DEAGLE"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:firearm" },
    ["MarzGuns.DETECTIVE_38"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.DOUBLEBARREL"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.EXPS1_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.EXPS3_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.ElcanX2_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.Elvorenstein_Tacticool_Knife"] = { tags = "base:cutplant;base:sharpknife;base:butcheranimal;base:sharpenable;base:killanimal;base:hasmetal" },
    ["MarzGuns.FAL"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.FAMAS"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.FNC"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.FNC_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.FNC_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.G3"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.G36"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.G36C"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.G36C_Integrated_Rail_Down"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.G36C_Integrated_Rail_Up"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.G36C_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.G36C_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.G36_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.G36_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.HIPOWER"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.Heavy_Pistol_Rail"] = { mountOn = "MarzGuns.DEAGLE;MarzGuns.PYTHON;MarzGuns.SW629" },
    ["MarzGuns.JS14_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.K98_BAYONET"] = { tags = "base:cutplant;base:sharpknife;base:butcheranimal;base:sharpenable;base:killanimal;base:hasmetal" },
    ["MarzGuns.K98_Bayonet_Attachment"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Kobra_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.LP_Light"] = { mountOn = "MarzGuns.M92FS;MarzGuns.HIPOWER;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.P226", tags = "base:flashlight;base:usesbattery" },
    ["MarzGuns.LR10X_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.LR2_Compensator"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.M4;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.M4A1;MarzGuns.M16A2_M203" },
    ["MarzGuns.LR4X_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.LRX-7_Laser"] = { mountOn = "MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.ASVAL;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.M4" },
    ["MarzGuns.LRX12X_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.LX_Flashhider"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.M4;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.M4A1;MarzGuns.M16A2_M203" },
    ["MarzGuns.Lever_Fired"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Lever_Lock"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M&P_Suppressor"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226" },
    ["MarzGuns.M14"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M16A1"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M16A2"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M16A2_M203"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M16A2_M203_Integrated"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M16A3"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M1895"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M1903"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M1911"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M1_GARAND"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M203"] = { mountOn = "MarzGuns.M4" },
    ["MarzGuns.M203_Weapon"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M24"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M24_Integrated_Bipod_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M24_Integrated_Bipod_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M4"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M4A1"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M4A1_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M4A1_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M4_Integrated_Rail_Down"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M4_Integrated_Rail_Left"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M4_Integrated_Rail_Right"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M4_Integrated_Rail_Up"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M5_BAYONET"] = { tags = "base:cutplant;base:sharpknife;base:butcheranimal;base:sharpenable;base:killanimal;base:hasmetal" },
    ["MarzGuns.M5_Bayonet_Attachment"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M60"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M60_Integrated_Bipod_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M60_Integrated_Bipod_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.M79"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M92FS"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M93R"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.M9_BAYONET"] = { tags = "base:cutplant;base:sharpknife;base:butcheranimal;base:sharpenable;base:killanimal;base:hasmetal" },
    ["MarzGuns.M9_Bayonet_Attachment"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.MAC10"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MAC10_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.MAC10_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.MASTERKEY"] = { mountOn = "MarzGuns.M16A2" },
    ["MarzGuns.MASTERKEY_Weapon"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MK2_Foregrip"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.MKC_Foregrip"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.MKI_Suppressor"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.M4;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.M4A1;MarzGuns.M16A2_M203" },
    ["MarzGuns.MOSIN"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MOSSBERG_590"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MP412"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MP5"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MP5A2"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MP5K"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MP5SD"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.MP5SD_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.MP5SD_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.MP5_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.MP5_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.NDR_Suppressor"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.M4;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.M4A1;MarzGuns.M16A2_M203" },
    ["MarzGuns.OKP3_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.P226"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.P45_Suppressor"] = { mountOn = "MarzGuns.M1911;MarzGuns.USP;MarzGuns.MAC10" },
    ["MarzGuns.PBS-1_Suppressor"] = { mountOn = "MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.AK47" },
    ["MarzGuns.PJ-3_Laser"] = { mountOn = "MarzGuns.M92FS;MarzGuns.HIPOWER;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.P226" },
    ["MarzGuns.PL4_Sight"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.PYTHON;MarzGuns.SW629" },
    ["MarzGuns.PM2_Sight"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.PYTHON;MarzGuns.SW629" },
    ["MarzGuns.PRL1_Scope"] = { mountOn = "MarzGuns.DEAGLE;MarzGuns.PYTHON;MarzGuns.SW629" },
    ["MarzGuns.PS1_Sight"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.PYTHON;MarzGuns.SW629" },
    ["MarzGuns.PSG1"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.PSO1_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.PX1_Laser"] = { mountOn = "MarzGuns.M92FS;MarzGuns.HIPOWER;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.P226" },
    ["MarzGuns.PYTHON"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.Picatinny_Rail"] = { mountOn = "MarzGuns.FakeItemRifles" },
    ["MarzGuns.Picatinny_Rail_Down"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.SVD;MarzGuns.PSG1;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD" },
    ["MarzGuns.Picatinny_Rail_Left"] = { mountOn = "MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.ASVAL;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD" },
    ["MarzGuns.Picatinny_Rail_Right"] = { mountOn = "MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.ASVAL;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD" },
    ["MarzGuns.Picatinny_Rail_Up"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K" },
    ["MarzGuns.Pistol_Muzzle_Mount_Device"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226" },
    ["MarzGuns.Pump_Fired"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Pump_Lock"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.REMINGTON_870"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.RHINO"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.ReflexS2_Sight"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.MP5K;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.SKS"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.SKS_Bayonet_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.SKS_Bayonet_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.SPAS12"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.SPAS12_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.SPAS12_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.SR7_Light"] = { mountOn = "MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.ASVAL;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.M4", tags = "base:flashlight;base:usesbattery" },
    ["MarzGuns.STEVENS_555"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.SVD"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.SW629"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.Shellholder"] = { mountOn = "MarzGuns.STEVENS_555;MarzGuns.DOUBLEBARREL" },
    ["MarzGuns.Shh9_Suppressor"] = { mountOn = "MarzGuns.M92FS;MarzGuns.M93R;MarzGuns.HIPOWER;MarzGuns.P226" },
    ["MarzGuns.Slide_Fired"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Slide_Lock"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.Sniper_Mount"] = { mountOn = "MarzGuns.MOSIN;MarzGuns.M1903" },
    ["MarzGuns.Stub_Foregrip"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.G36;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.AA12;MarzGuns.MP5;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.TA28_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.TEC9"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.THOMPSON"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.TL_Light"] = { mountOn = "MarzGuns.M92FS;MarzGuns.HIPOWER;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.P226", tags = "base:flashlight;base:usesbattery" },
    ["MarzGuns.TOZ34"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.TR-1_Laser"] = { mountOn = "MarzGuns.M92FS;MarzGuns.HIPOWER;MarzGuns.M1911;MarzGuns.USP;MarzGuns.DEAGLE;MarzGuns.P226" },
    ["MarzGuns.TR06X_Scope"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A2_M203;MarzGuns.M16A3;MarzGuns.AR15;MarzGuns.FNC;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.XM177;MarzGuns.M4A1;MarzGuns.M14;MarzGuns.FAL;MarzGuns.G3;MarzGuns.M24;MarzGuns.MOSSBERG_590;MarzGuns.BENELLI_M4;MarzGuns.REMINGTON_870;MarzGuns.PSG1;MarzGuns.W1894;MarzGuns.M1895;MarzGuns.W1887;MarzGuns.W1873;MarzGuns.MP5A2;MarzGuns.MP5SD;MarzGuns.AK74;MarzGuns.AKS74U;MarzGuns.ASVAL;MarzGuns.SVD;MarzGuns.AK47;MarzGuns.MOSIN;MarzGuns.M1903;MarzGuns.G36C;MarzGuns.M4" },
    ["MarzGuns.TRENCHGUN"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.Trix42_Muzzlebreak"] = { mountOn = "MarzGuns.M16A1;MarzGuns.M16A2;MarzGuns.M16A3;MarzGuns.M4;MarzGuns.G36C;MarzGuns.G36;MarzGuns.FAMAS;MarzGuns.CAR15;MarzGuns.M4A1;MarzGuns.M16A2_M203" },
    ["MarzGuns.USP"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.VP70M"] = { tags = "base:hasmetal;base:ignorezombiedensity;base:firearm" },
    ["MarzGuns.VP70M_Stock"] = { mountOn = "MarzGuns.VP70M" },
    ["MarzGuns.W1873"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.W1873_CARBINE"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.W1887"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.W1894"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.XM177"] = { tags = "base:hasmetal;base:firearm" },
    ["MarzGuns.XM177_Integrated_Stock_Deployed"] = { mountOn = "MarzGuns.FakeItem" },
    ["MarzGuns.XM177_Integrated_Stock_Folded"] = { mountOn = "MarzGuns.FakeItem" },
}

return data
