-- Auto-generated model capability map from the supplied Guns of Marz 42.16 scripts.
-- It contains only direct WeaponPart MountOn relationships. Runtime Gunworks
-- universal rails, bayonets and actually installed parts are merged separately.
-- Generated for Inspect Weapon - Guns of Marz Compatibility Fix 4.

local capabilities = {
    ["MarzGuns.AA12"] = { Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true },
    ["MarzGuns.AK47"] = { BoosterScope = true, Canon = true, CanonMount = true, RailUp = true, Scope = true },
    ["MarzGuns.AK74"] = { BoosterScope = true, Canon = true, CanonMount = true, RailUp = true, Scope = true },
    ["MarzGuns.AKS74U"] = { BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.AR15"] = { Bipod = true, BoosterScope = true, Foregrip = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.ASVAL"] = { BoosterScope = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.BENELLI_M4"] = { RailUp = true, Scope = true },
    ["MarzGuns.CAR15"] = { BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.DEAGLE"] = { RailUp = true, Scope = true, Underbarrel = true },
    ["MarzGuns.DOUBLEBARREL"] = { Shellholder = true },
    ["MarzGuns.FAL"] = { Bipod = true, BoosterScope = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.FAMAS"] = { Canon = true, CanonMount = true, Foregrip = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.FNC"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.G3"] = { Bipod = true, BoosterScope = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.G36"] = { Bipod = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true },
    ["MarzGuns.G36C"] = { Bipod = true, BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailLeft = true, RailRight = true, Scope = true },
    ["MarzGuns.HIPOWER"] = { Canon = true, CanonMount = true, RailUp = true, Scope = true, Underbarrel = true },
    ["MarzGuns.M14"] = { Bipod = true, BoosterScope = true, Foregrip = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.M16A1"] = { Bipod = true, BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.M16A2"] = { Bipod = true, BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true, Underbarrel = true },
    ["MarzGuns.M16A2_M203"] = { BoosterScope = true, Canon = true, CanonMount = true, RailUp = true, Scope = true },
    ["MarzGuns.M16A3"] = { Bipod = true, BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.M1895"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.M1903"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.M1911"] = { Canon = true, CanonMount = true, RailUp = true, Scope = true, Underbarrel = true },
    ["MarzGuns.M24"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.M4"] = { Bipod = true, BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, Scope = true, Underbarrel = true },
    ["MarzGuns.M4A1"] = { Bipod = true, BoosterScope = true, Canon = true, CanonMount = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.M92FS"] = { Canon = true, CanonMount = true, RailUp = true, Scope = true, Stock = true, Underbarrel = true },
    ["MarzGuns.M93R"] = { Canon = true, CanonMount = true, RailUp = true, Scope = true, Stock = true },
    ["MarzGuns.MAC10"] = { Canon = true, CanonMount = true },
    ["MarzGuns.MOSIN"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.MOSSBERG_590"] = { RailUp = true, Scope = true },
    ["MarzGuns.MP5"] = { Bipod = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.MP5A2"] = { Bipod = true, BoosterScope = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.MP5K"] = { RailUp = true, Scope = true },
    ["MarzGuns.MP5SD"] = { Bipod = true, BoosterScope = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
    ["MarzGuns.P226"] = { Canon = true, CanonMount = true, RailUp = true, Scope = true, Underbarrel = true },
    ["MarzGuns.PSG1"] = { Bipod = true, BoosterScope = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.PYTHON"] = { RailUp = true, Scope = true },
    ["MarzGuns.REMINGTON_870"] = { RailUp = true, Scope = true },
    ["MarzGuns.STEVENS_555"] = { Shellholder = true },
    ["MarzGuns.SVD"] = { Bipod = true, BoosterScope = true, RailDown = true, RailUp = true, Scope = true },
    ["MarzGuns.SW629"] = { RailUp = true, Scope = true },
    ["MarzGuns.USP"] = { Canon = true, CanonMount = true, RailUp = true, Scope = true, Underbarrel = true },
    ["MarzGuns.VP70M"] = { Stock = true },
    ["MarzGuns.W1873"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.W1887"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.W1894"] = { BoosterScope = true, RailUp = true, Scope = true },
    ["MarzGuns.XM177"] = { Bipod = true, BoosterScope = true, Foregrip = true, LaserRifle = true, LightRifle = true, RailDown = true, RailLeft = true, RailRight = true, RailUp = true, Scope = true },
}

return capabilities
